"""Auto Migration

Revision ID: 772978814191
Revises: 
Create Date: 2026-08-05 21:39:25.565578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772978814191'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=30), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index(op.f('ix_employee_master_id'), 'employee_master', ['id'], unique=False)
    op.create_table('salary_head_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_head', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salary_head')
    )
    op.create_index(op.f('ix_salary_head_master_id'), 'salary_head_master', ['id'], unique=False)
    op.create_table('one_time_payroll_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('salary_head_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_master.id'], ),
    sa.ForeignKeyConstraint(['salary_head_id'], ['salary_head_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'salary_head_id', 'month', 'year', name='uq_payroll_entry')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one_time_payroll_entry')
    op.drop_index(op.f('ix_salary_head_master_id'), table_name='salary_head_master')
    op.drop_table('salary_head_master')
    op.drop_index(op.f('ix_employee_master_id'), table_name='employee_master')
    op.drop_table('employee_master')
    # ### end Alembic commands ###
